import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "../provider/TanstackProvider";
import { ReduxProvider } from "../provider/ReactProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TanstackProvider>
            <div className="flex justify-center">
              <div className="container">
            {children}

              </div>
            </div>
            
            </TanstackProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
